import Head from 'next/head'
import Image from 'next/image'
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative min-h-screen pl-80 bg-gray-900">
        <div className="absolute bottom-0 left-40 mb-60">
          <h1 className="text-8xl uppercase tracking-tighter shimmer">
            Shawn
            <br />
            Harrington
          </h1>
          <h2 className="text-6xl uppercase tracking-tighter">
            <span className="text-orange-600">Full Stack</span>{" "}
            <span className="text-orange-400">Software</span>{" "}
            <span className="text-orange-600">Engineer</span>
          </h2>
          <div className="mt-5">
            <button className="rounded text-2xl px-8 py-3 bg-black text-white hover:bg-white hover:text-black hover:border-black hover:border">
              <strong>About Me</strong>
            </button>
            <button className="ml-3 rounded text-2xl px-8 py-3 bg-black text-white hover:bg-white hover:text-black hover:border-black hover:border">
              <strong>Hire Me</strong>
            </button>
          </div>
        </div>
      </main>
      <div className="bg-orange-600 text-gray-300 pl-40">
        <p className="text-4xl py-10 max-w-3xl">
          I am an <strong className="text-white">enthusiastic developer</strong>{" "}
          with a strong addiction to discovering{" "}
          <strong className="text-white">new coding perspectives.</strong>
        </p>
      </div>
      <div className="pl-40 pt-20 text-3xl bg-gray-900 text-white">
        <h2 className="font-bold">PROJECTS</h2>
      </div>
    </>
  );
}
